# Generated by Django 4.2.4 on 2023-09-14 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CelTech', '0002_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
