# Generated by Django 4.2.4 on 2023-09-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CelTech', '0004_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Celulares',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
