# Generated by Django 4.2.4 on 2023-09-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CelTech', '0007_celulares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
