# Generated by Django 4.2.4 on 2023-09-14 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CelTech', '0008_accesorios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Clientes',
        ),
    ]
