# Generated by Django 4.2.4 on 2023-09-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CelTech', '0010_fundas'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.EmailField(default=False, max_length=254),
            preserve_default=False,
        ),
    ]
