# Generated by Django 4.2.4 on 2023-09-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CelTech', '0011_clientes_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
