# Generated by Django 4.2.4 on 2023-10-01 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CelTech', '0012_consulta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
