# Generated by Django 4.2.4 on 2023-10-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CelTech', '0013_delete_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
